import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";

const roboto = Roboto({ subsets: ["latin"],weight: ["300","400","700","500"] ,variable: "--font-roboto"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
